site_articles/src/Entity/Critique.php
<?php

namespace App\Entity;

use App\Repository\CritiqueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CritiqueRepository::class)
 */
class Critique
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $critique;

    /**
     * @ORM\ManyToOne(targetEntity=Book::class, inversedBy="critiques")
     * @ORM\JoinColumn(nullable=false)
     */
    private $book;

    /**
     * @ORM\ManyToOne(targetEntity=Film::class, inversedBy="critiques")
     * @ORM\JoinColumn(nullable=false)
     */
    private $film;

    /**
     * @ORM\ManyToOne(targetEntity=Critic::class, inversedBy="critiques")
     * @ORM\JoinColumn(nullable=false)
     */
    private $critic;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="critique")
     */
    private $notes;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getCritique(): ?string
    {
        return $this->critique;
    }

    public function setCritique(string $critique): self
    {
        $this->critique = $critique;

        return $this;
    }

    public function getBook(): ?Book
    {
        return $this->book;
    }

    public function setBook(?Book $book): self
    {
        $this->book = $book;

        return $this;
    }

    public function getFilm(): ?Film
    {
        return $this->film;
    }

    public function setFilm(?Film $film): self
    {
        $this->film = $film;

        return $this;
    }

    public function getCritic(): ?Critic
    {
        return $this->critic;
    }

    public function setCritic(?Critic $critic): self
    {
        $this->critic = $critic;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setCritique($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getCritique() === $this) {
                $note->setCritique(null);
            }
        }

        return $this;
    }
}

site_articles/src/Controller/SiteController.php
<?php

namespace App\Controller;

use App\Entity\Film;
use App\Entity\Book;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SiteController extends AbstractController
{
    /**
     * @Route("/site_films", name="index_films")
     */
    public function index_films(): Response
    {
        $repoB = $this-> getDoctrine()->getRepository(Book::class);
        $repoF = $this-> getDoctrine()->getRepository(Film::class);
        $books = $repoB-> findAll();
        $films = $repoF-> findAll();
        $i = 1;
        $filmsP1 = array();
        $filmsP2 = array();
        /*
        foreach ($repoF-> findAll() as $film) {
            if ($i%2 == 1) {
                $filmsP1[$i] = $film;
            }
            elseif ($i%2 == 0) {
                $filmsP2[$i] = $film;
            }
            $i++;
        }
*/
        return $this->render('site/index_films.html.twig', [
            'controller_name' => 'SiteController',
            'books' => $books,
            //'filmsP1' => $filmsP1,
            //'filmsP2' => $filmsP2
            'films' => $films
        ]);
    }
    /**
     * @Route("/site_books", name="index_books")
     */
    public function index_books(): Response
    {
        $repo = $this->getDoctrine()->getRepository(Book::class);
        $books = $repo->findAll();

        return $this->render('site/index_books.html.twig', [
            'controller_name' => 'SiteController',
            'books' => $books
        ]);
    }
    /**
     * @Route("/", name="home")
     */
    public function home(): Response
    {
        return $this->render('site/home.html.twig', [
            'controller_name' => 'SiteController',
        ]);
    }
    /**
     * @Route("/site/film{filmID}", name="show_critique_film")
     */
    public function film($filmID): Response
    {
        $repo = $this->getDoctrine()->getRepository(Film::class);
        $film = $repo->find($filmID);
        $note = 0;
        foreach ($film->getNotes() as $value) {
            $note = $note+$value->getValue();
        }
        $note = intval($note/count($film->getNotes()));


        return $this->render('site/film.html.twig', [
            'controller_name' => 'SiteController',
            'film' => $film,
            'note' => $note
        ]);
    }
    /**
     * @Route("/site/book{bookID}", name="show_critique_book")
     */
    public function book($bookID): Response
    {
        $repo = $this->getDoctrine()->getRepository(Book::class);
        $book = $repo->find($bookID);
        $note = 0;
        foreach ($book->getNotes() as $value) {
            $note = $note+$value->getValue();
        }
        $note = intval($note/count($book->getNotes()));

        return $this->render('site/book.html.twig', [
            'controller_name' => 'SiteController',
            'book' => $book,
            'note' => $note
        ]);
    }
}

site_articles/templates/site/book.html.twig
{% extends "base.html.twig" %}
{% block body %}

<h1>{{ book.title }}</h1>
<div>
    <img src="http://placehold.it/350x200" border="0" ALIGN="Left">
    <p> &nbsp; Auteur : {{ book.author }}</p>
    <p> &nbsp; Type : {{ book.type }}</p>
    <p> &nbsp; Date de sortie : {{ book.releaseDate | date('d/m/y')}}</p>
    <p> &nbsp; Nationnalité : {{ book.citizenship }}</p>
    <p> &nbsp; Note : {{ note }}/5</p>
    <p> &nbsp;</p>
</div>


<h3>Résumer : </h3>
<p> {{ book.cover }}</p>

<hr>

{% for critique in book.critiques %}
    <div class="card bg-light mb-3" style="max-width: 20rem;">
    <div class="card-header"> 
        {{ critique.critic.pseudo }}
    </div>
    <div class="card-body">
        <p class="card-text"> {{ critique.critique }}</p>
    </div>
    </div>
{% endfor %}



{% endblock %}

site_articles/templates/site/film.html.twig
{% extends "base.html.twig" %}
{% block body %}

<h1>{{ film.title }}</h1>
<div>
    <img src="http://placehold.it/350x200" border="0" ALIGN="Left">
    <p> &nbsp; Auteur : {{ film.author }}</p>
    <p> &nbsp; Type : {{ film.type }}</p>
    <p> &nbsp; Date de sortie : {{ film.releaseDate | date('d/m/y')}}</p>
    <p> &nbsp; Nationnalité : {{ film.citizenship }}</p>
    <p> &nbsp; Note : {{ note }}/5</p>
    <p> &nbsp;</p>
</div>

<p> Synopsis : {{ film.synopsis }}</p>

<hr>

{% for critique in film.critiques %}
    <div class="card bg-light mb-3" style="max-width: 20rem;">
    <div class="card-header"> 
        {{ critique.critic.pseudo }}
    </div>
    <div class="card-body">
        <p class="card-text"> {{ critique.critique }}</p>
    </div>
    </div>
{% endfor %}


{% endblock %}

site_articles/templates/site/home.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://bootswatch.com/4/minty/bootstrap.min.css">
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>  
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand mx-auto" href="{{ path('home') }}">Site de critiques</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button> 
        </nav>         
        <div class="container"> 
        {% block body %}
            <h1> Page d'acceuil </h1>
            <p> 
                <a href="{{ path('index_films') }}">Cliquer ici</a> pour accèder à la liste des critiques de film. 
            </p>
            <p> 
                <a href="{{ path('index_books') }}">Cliquer ici</a> pour accèder à la liste des critiques de livre. 
            </p>
        {% endblock %} </div>
    </body>
</html>

site_articles/templates/site/index.html.twig
{% extends "base.html.twig" %}
{% block body %}

<h1>Page de critique des films</h1>

<section class="articles">
    {% for film in films %}
      <article>
        <h3> {{ film.title }}</h3>  
        <div>
          <img src="http://placehold.it/200x100">
        </div>
        <p>Auteur : {{ film.author }}</p>
        <p>Type : {{ film.type }}</p>
        <p>Date de sortie : {{ film.releaseDate | date('d/m/y')}}</p>
        <p>Nationnalité : {{ film.citizenship }}</p>
        <a href="{{ path('show_critique_film', {'id':film.id}) }}">Lire la suite</a>
        <hr>
      </article>
    {% endfor %}
  </tbody>
</section>


{% endblock %}

site_articles/templates/site/index_books.html.twig
{% extends "base.html.twig" %}
{% block body %}

<h1>Page de critique des livres</h1>

<section class="articles">
    {% for book in books %}
      <article>
        <h3> {{ book.title }}</h3>  
        <div>
          <img src="http://placehold.it/200x100">
        </div>
        <p>Auteur : {{ book.author }}</p>
        <p>Type : {{ book.type }}</p>
        <p>Date de sortie : {{ book.releaseDate | date('d/m/y')}}</p>
        <p>Nationnalité : {{ book.citizenship }}</p>
        <a href="{{ path('show_critique_book', {'bookID':book.id}) }}">Lire la suite</a>
        <hr>
      </article>
    {% endfor %}
  </tbody>
</section>


{% endblock %}

site_articles/templates/site/index_films.html.twig
{% extends "base.html.twig" %}
{% block body %}

<h1>Page de critique des films</h1>

<section class="articles">
    {% for film in films %}
      <article>
        <h3> {{ film.title }}</h3>  
        <div>
          <img src="http://placehold.it/200x100">
        </div>
        <p>Auteur : {{ film.author }}</p>
        <p>Type : {{ film.type }}</p>
        <p>Date de sortie : {{ film.releaseDate | date('d/m/y')}}</p>
        <p>Nationnalité : {{ film.citizenship }}</p>
        <a href="{{ path('show_critique_film', {'filmID':film.id}) }}">Lire la suite</a>
        <hr>
      </article>
    {% endfor %}
  </tbody>
</section>


{% endblock %}